require 'datenfisch/nodes/attribute'
require 'datenfisch/nodes/literal'
require 'datenfisch/nodes/combinator'
require 'datenfisch/nodes/arithmetic'
require 'datenfisch/nodes/predicates'
require 'datenfisch/nodes/aggregates'
